### PR TITLE
Update 14.0

### PR DESCRIPTION
**Pull request by christophlsa**

### CODE REVIEW

**Comment by christophlsa** [comment]
To rebase our latest changes:
```
git fetch origin
git checkout 14.0-rebase   # in case you are not in the branch
git rebase origin/jobrad-14.0
git push -f
```

To update with the latest changes:
```
git remote add odoo git@github.com:odoo/odoo.git
git fetch odoo
git checkout 14.0-rebase   # in case you are not in the branch
git rebase odoo/14.0
git push -f
```

**Comment by christophlsa** [comment]
```
git fetch origin
git remote add odoo git@github.com:odoo/odoo.git
git fetch odoo
git checkout 14.0-rebase   # in case you are not in the branch
git reset --hard origin/jobrad-14.0   # throw all changes away - be careful if there are changes we need to keep
git rebase odoo/14.0
git cherry-pick 908d68087be0bd2f270722c671ad1637fa94ee54   # andreas commit which reverts one change
git push -f
```

**Comment by anoop-rad** [comment]
@christophlsa 
Can you have a look at the conflict in the Dockerfile?

**Comment by christophlsa** [comment]
I applied the steps from https://github.com/jobrad-gmbh/odoo/pull/7#issuecomment-2034827231

But I used the commit `b917cd6af89d168bbf72e8253a6d7fa5193d6553` instead of `odoo/14.0` for the rebase to only fix the merge conflict without updating with the newest upstream changes.

If you want the newest upstream changes just tell me and I run the commands again or do it by yourself. :D

**Pull request merged**
